[workspace]
members = ["programs/nft-staking"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./staking-wallet.json"

[programs.mainnet]
nft_staking = "JCnPzmQxxP6XTJAj5nf173Rk5rxtag5dQjgvsb9tQDYA"

[scripts]
test = "ts-mocha --path tsconfig.json -t 1000000 tests/nft-staking/*.ts"
